### ISSUE TITLE
unable to save data

### ISSUE THREAD

**Issue by Abunchoftrash** [jval1972/ENDEDIT#1]
for an unknown reason, saving does not work properly

I created a graphic, pressed save, and went to view it in my software. It is completely unchanged from how I left it before editing today.

**Comment by jval1972** [comment]
Can you please provide some more information:
What do you mean "view it in your software". What software? When saved from ENDEDIT and opened back from ENDEDIT do the changes appear? Is there a back-up file with the date/time of your last save? Did any error message appeared during your last save? Was the file already opened by another app? Did you accidentally press the Undo button?

**Comment by Abunchoftrash** [comment]
I am using ENDEDIT version 1.0.1.9

1: My software is Slade 3, the Doom editing software.
2: Changes appear in ENDEDIT but reading the created file in any other software reverts to before creating.
3: There is a backup, but saving with that doesn't work either
4: There were no error messages whatsoever
5: No, only ENDEDIT was accessing the file
6: Its kinda a conscious effort to continually spam the undo button several times

**Comment by jval1972** [comment]
Are you sure that you open the exact same file with any other software? In Slade 3 are you working with a wad or a pk3 archive or in directory mode?  ENDEDIT saves individual files with the .BIN default extention, Slade3 can not open such files, it can only import them in a archive (WAD/PK3). Slade3 in order to display correctly an ENDEDIT screen, the filename must be a known ENDSCREEN name, such as ENDOOM, ENDTEXT or ENDSTRF. It will not work with a random filename.

**Comment by Abunchoftrash** [comment]
I have come to the disappointing conclusion that i was putting the wrong iteration of the file into the pk3
sincere apologies
